import { Suspense } from 'react'
import './globals.css'
import Header from './header'
import Banner from './banner'
import Provider from './provider'


export const metadata = {
  title: 'dev blog',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='scroll-smooth antialiased'>
      <body className="max-w-screen-2xl mx-auto">
        <Provider>
            <Header />
            <Banner />
            <Suspense fallback={<p>Loading feed...</p>}>
               {children}  
           </Suspense>               
        </Provider>

      </body>
    </html>
  )
}
