// import { Suspense } from 'react'
import './globals.css'
import Header from './components/header'
import Banner from './components/banner'
import Provider from './components/provider'
// import Footer from './footer'


export const metadata = {
  title: 'dev blog',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='scroll-smooth antialiased'>
      <body className="max-w-screen-2xl mx-auto">
        <Provider>
            <Header />
            <Banner />
            {/* <Suspense fallback={<p>Loading feed...</p>}> */}
               {children}  
           {/* </Suspense>                */}
        </Provider>
        {/* <Footer/> */}
      </body>
    </html>
  )
}
